package com.manager.response;

import java.io.Serializable;

import com.manager.enums.PlatformTypeEnum;

public class UserCustomResponse implements Serializable{
	
	 /**
	 * 
	 */
	private Integer id;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.user_id
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer userId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.send_province
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private String sendProvince;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.send_city
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private String sendCity;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.receive_province
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private String receiveProvince;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.receive_city
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private String receiveCity;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_send
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isSend;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_receive
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isReceive;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_receive_self
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isReceiveSelf;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_manager
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isManager;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.username
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private String username;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.platform_type
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private PlatformTypeEnum platformType;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_binding
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isBinding;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_phone_limit
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isPhoneLimit;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_receive_car
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isReceiveCar;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_receive_goods
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isReceiveGoods;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_send_car
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isSendCar;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_send_goods
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isSendGoods;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column user_custom.is_look_phone
	     *
	     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
	     */
	    private Integer isLookPhone;

		public Integer getId() {
			return id;
		}

		public void setId(Integer id) {
			this.id = id;
		}

		public Integer getUserId() {
			return userId;
		}

		public void setUserId(Integer userId) {
			this.userId = userId;
		}

		public String getSendProvince() {
			return sendProvince;
		}

		public void setSendProvince(String sendProvince) {
			this.sendProvince = sendProvince;
		}

		public String getSendCity() {
			return sendCity;
		}

		public void setSendCity(String sendCity) {
			this.sendCity = sendCity;
		}

		public String getReceiveProvince() {
			return receiveProvince;
		}

		public void setReceiveProvince(String receiveProvince) {
			this.receiveProvince = receiveProvince;
		}

		public String getReceiveCity() {
			return receiveCity;
		}

		public void setReceiveCity(String receiveCity) {
			this.receiveCity = receiveCity;
		}

		public Integer getIsSend() {
			return isSend;
		}

		public void setIsSend(Integer isSend) {
			this.isSend = isSend;
		}

		public Integer getIsReceive() {
			return isReceive;
		}

		public void setIsReceive(Integer isReceive) {
			this.isReceive = isReceive;
		}

		public Integer getIsReceiveSelf() {
			return isReceiveSelf;
		}

		public void setIsReceiveSelf(Integer isReceiveSelf) {
			this.isReceiveSelf = isReceiveSelf;
		}

		public Integer getIsManager() {
			return isManager;
		}

		public void setIsManager(Integer isManager) {
			this.isManager = isManager;
		}

		public String getUsername() {
			return username;
		}

		public void setUsername(String username) {
			this.username = username;
		}

		public PlatformTypeEnum getPlatformType() {
			return platformType;
		}

		public void setPlatformType(PlatformTypeEnum platformType) {
			this.platformType = platformType;
		}

		public Integer getIsBinding() {
			return isBinding;
		}

		public void setIsBinding(Integer isBinding) {
			this.isBinding = isBinding;
		}

		public Integer getIsPhoneLimit() {
			return isPhoneLimit;
		}

		public void setIsPhoneLimit(Integer isPhoneLimit) {
			this.isPhoneLimit = isPhoneLimit;
		}

		public Integer getIsReceiveCar() {
			return isReceiveCar;
		}

		public void setIsReceiveCar(Integer isReceiveCar) {
			this.isReceiveCar = isReceiveCar;
		}

		public Integer getIsReceiveGoods() {
			return isReceiveGoods;
		}

		public void setIsReceiveGoods(Integer isReceiveGoods) {
			this.isReceiveGoods = isReceiveGoods;
		}

		public Integer getIsSendCar() {
			return isSendCar;
		}

		public void setIsSendCar(Integer isSendCar) {
			this.isSendCar = isSendCar;
		}

		public Integer getIsSendGoods() {
			return isSendGoods;
		}

		public void setIsSendGoods(Integer isSendGoods) {
			this.isSendGoods = isSendGoods;
		}

		public Integer getIsLookPhone() {
			return isLookPhone;
		}

		public void setIsLookPhone(Integer isLookPhone) {
			this.isLookPhone = isLookPhone;
		}


		@Override
		public String toString() {
			return "UserCustomResponse [id=" + id + ", userId=" + userId + ", sendProvince=" + sendProvince
					+ ", sendCity=" + sendCity + ", receiveProvince=" + receiveProvince + ", receiveCity=" + receiveCity
					+ ", isSend=" + isSend + ", isReceive=" + isReceive + ", isReceiveSelf=" + isReceiveSelf
					+ ", isManager=" + isManager + ", username=" + username + ", platformType=" + platformType
					+ ", isBinding=" + isBinding + ", isPhoneLimit=" + isPhoneLimit + ", isReceiveCar=" + isReceiveCar
					+ ", isReceiveGoods=" + isReceiveGoods + ", isSendCar=" + isSendCar + ", isSendGoods=" + isSendGoods
					+ ", isLookPhone=" + isLookPhone + "]";
		}
	    
	    
	
	
}
