package com.manager.mapper;

import com.manager.pojo.Advert;
import com.manager.pojo.AdvertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AdvertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int countByExample(AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int deleteByExample(AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int insert(Advert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int insertSelective(Advert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    List<Advert> selectByExample(AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    Advert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") Advert record, @Param("example") AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int updateByExample(@Param("record") Advert record, @Param("example") AdvertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int updateByPrimaryKeySelective(Advert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advert
     *
     * @mbggenerated Sat Apr 01 09:33:56 CST 2017
     */
    int updateByPrimaryKey(Advert record);
}