package com.manager.mapper;

import com.manager.pojo.BannerInfo;
import com.manager.pojo.BannerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface BannerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int countByExample(BannerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int deleteByExample(BannerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int insert(BannerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int insertSelective(BannerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    List<BannerInfo> selectByExample(BannerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    BannerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") BannerInfo record, @Param("example") BannerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int updateByExample(@Param("record") BannerInfo record, @Param("example") BannerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int updateByPrimaryKeySelective(BannerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int updateByPrimaryKey(BannerInfo record);
}