package com.manager.mapper;

import com.manager.pojo.HotCity;
import com.manager.pojo.HotCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface HotCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int countByExample(HotCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int deleteByExample(HotCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int insert(HotCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int insertSelective(HotCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    List<HotCity> selectByExampleWithBLOBs(HotCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    List<HotCity> selectByExample(HotCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    HotCity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") HotCity record, @Param("example") HotCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") HotCity record, @Param("example") HotCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int updateByExample(@Param("record") HotCity record, @Param("example") HotCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int updateByPrimaryKeySelective(HotCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(HotCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    int updateByPrimaryKey(HotCity record);
}