package com.manager.mapper;

import com.manager.pojo.Query;
import com.manager.pojo.QueryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface QueryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int countByExample(QueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int deleteByExample(QueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int insert(Query record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int insertSelective(Query record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    List<Query> selectByExample(QueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    Query selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") Query record, @Param("example") QueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int updateByExample(@Param("record") Query record, @Param("example") QueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int updateByPrimaryKeySelective(Query record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table query
     *
     * @mbggenerated Wed Apr 19 11:11:58 CST 2017
     */
    int updateByPrimaryKey(Query record);
}