package com.manager.mapper;

import com.manager.pojo.UserCustom;
import com.manager.pojo.UserCustomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserCustomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int countByExample(UserCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int deleteByExample(UserCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int insert(UserCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int insertSelective(UserCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    List<UserCustom> selectByExample(UserCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    UserCustom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserCustom record, @Param("example") UserCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int updateByExample(@Param("record") UserCustom record, @Param("example") UserCustomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int updateByPrimaryKeySelective(UserCustom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    int updateByPrimaryKey(UserCustom record);
}