package com.manager.mapper;

import com.manager.pojo.UserBinding;
import com.manager.pojo.UserBindingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserBindingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int countByExample(UserBindingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int deleteByExample(UserBindingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int insert(UserBinding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int insertSelective(UserBinding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    List<UserBinding> selectByExample(UserBindingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    UserBinding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserBinding record, @Param("example") UserBindingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int updateByExample(@Param("record") UserBinding record, @Param("example") UserBindingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int updateByPrimaryKeySelective(UserBinding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    int updateByPrimaryKey(UserBinding record);
}