package com.manager.pojo;

import com.manager.request.BaseEntity;
import java.util.Date;

public class Admin extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_name
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.passwd
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.role
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.be_used
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    private Integer beUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_time
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_name
     *
     * @return the value of admin.user_name
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_name
     *
     * @param userName the value for admin.user_name
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.passwd
     *
     * @return the value of admin.passwd
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.passwd
     *
     * @param passwd the value for admin.passwd
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.role
     *
     * @return the value of admin.role
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.role
     *
     * @param role the value for admin.role
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.be_used
     *
     * @return the value of admin.be_used
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public Integer getBeUsed() {
        return beUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.be_used
     *
     * @param beUsed the value for admin.be_used
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public void setBeUsed(Integer beUsed) {
        this.beUsed = beUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_time
     *
     * @return the value of admin.create_time
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_time
     *
     * @param createTime the value for admin.create_time
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Admin other = (Admin) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getPasswd() == null ? other.getPasswd() == null : this.getPasswd().equals(other.getPasswd()))
            && (this.getRole() == null ? other.getRole() == null : this.getRole().equals(other.getRole()))
            && (this.getBeUsed() == null ? other.getBeUsed() == null : this.getBeUsed().equals(other.getBeUsed()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri Mar 31 11:32:07 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPasswd() == null) ? 0 : getPasswd().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        result = prime * result + ((getBeUsed() == null) ? 0 : getBeUsed().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}