package com.manager.pojo;

import com.manager.enums.YesNoEnum;
import com.manager.request.BaseEntity;
import java.util.Date;

public class BannerInfo extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_info.id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_info.banner_name
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private String bannerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_info.image_url
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_info.be_used
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private YesNoEnum beUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_info.sort
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_info.create_time
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_info.id
     *
     * @return the value of banner_info.id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_info.id
     *
     * @param id the value for banner_info.id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_info.banner_name
     *
     * @return the value of banner_info.banner_name
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public String getBannerName() {
        return bannerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_info.banner_name
     *
     * @param bannerName the value for banner_info.banner_name
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setBannerName(String bannerName) {
        this.bannerName = bannerName == null ? null : bannerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_info.image_url
     *
     * @return the value of banner_info.image_url
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_info.image_url
     *
     * @param imageUrl the value for banner_info.image_url
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_info.be_used
     *
     * @return the value of banner_info.be_used
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public YesNoEnum getBeUsed() {
        return beUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_info.be_used
     *
     * @param beUsed the value for banner_info.be_used
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setBeUsed(YesNoEnum beUsed) {
        this.beUsed = beUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_info.sort
     *
     * @return the value of banner_info.sort
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_info.sort
     *
     * @param sort the value for banner_info.sort
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_info.create_time
     *
     * @return the value of banner_info.create_time
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_info.create_time
     *
     * @param createTime the value for banner_info.create_time
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BannerInfo other = (BannerInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBannerName() == null ? other.getBannerName() == null : this.getBannerName().equals(other.getBannerName()))
            && (this.getImageUrl() == null ? other.getImageUrl() == null : this.getImageUrl().equals(other.getImageUrl()))
            && (this.getBeUsed() == null ? other.getBeUsed() == null : this.getBeUsed().equals(other.getBeUsed()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner_info
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBannerName() == null) ? 0 : getBannerName().hashCode());
        result = prime * result + ((getImageUrl() == null) ? 0 : getImageUrl().hashCode());
        result = prime * result + ((getBeUsed() == null) ? 0 : getBeUsed().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}