package com.manager.pojo;

import com.manager.enums.PlatformTypeEnum;
import com.manager.request.BaseEntity;
import java.util.Date;

public class ClientUpgradeInfo extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_upgrade_info.id
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_upgrade_info.name
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_upgrade_info.version
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_upgrade_info.package_url
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    private String packageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_upgrade_info.upgrade_desc
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    private String upgradeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_upgrade_info.platform_type
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    private PlatformTypeEnum platformType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_upgrade_info.create_time
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_upgrade_info.id
     *
     * @return the value of client_upgrade_info.id
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_upgrade_info.id
     *
     * @param id the value for client_upgrade_info.id
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_upgrade_info.name
     *
     * @return the value of client_upgrade_info.name
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_upgrade_info.name
     *
     * @param name the value for client_upgrade_info.name
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_upgrade_info.version
     *
     * @return the value of client_upgrade_info.version
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_upgrade_info.version
     *
     * @param version the value for client_upgrade_info.version
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_upgrade_info.package_url
     *
     * @return the value of client_upgrade_info.package_url
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public String getPackageUrl() {
        return packageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_upgrade_info.package_url
     *
     * @param packageUrl the value for client_upgrade_info.package_url
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public void setPackageUrl(String packageUrl) {
        this.packageUrl = packageUrl == null ? null : packageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_upgrade_info.upgrade_desc
     *
     * @return the value of client_upgrade_info.upgrade_desc
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public String getUpgradeDesc() {
        return upgradeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_upgrade_info.upgrade_desc
     *
     * @param upgradeDesc the value for client_upgrade_info.upgrade_desc
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public void setUpgradeDesc(String upgradeDesc) {
        this.upgradeDesc = upgradeDesc == null ? null : upgradeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_upgrade_info.platform_type
     *
     * @return the value of client_upgrade_info.platform_type
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public PlatformTypeEnum getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_upgrade_info.platform_type
     *
     * @param platformType the value for client_upgrade_info.platform_type
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public void setPlatformType(PlatformTypeEnum platformType) {
        this.platformType = platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_upgrade_info.create_time
     *
     * @return the value of client_upgrade_info.create_time
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_upgrade_info.create_time
     *
     * @param createTime the value for client_upgrade_info.create_time
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_upgrade_info
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClientUpgradeInfo other = (ClientUpgradeInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getPackageUrl() == null ? other.getPackageUrl() == null : this.getPackageUrl().equals(other.getPackageUrl()))
            && (this.getUpgradeDesc() == null ? other.getUpgradeDesc() == null : this.getUpgradeDesc().equals(other.getUpgradeDesc()))
            && (this.getPlatformType() == null ? other.getPlatformType() == null : this.getPlatformType().equals(other.getPlatformType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_upgrade_info
     *
     * @mbggenerated Thu Apr 13 17:22:56 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getPackageUrl() == null) ? 0 : getPackageUrl().hashCode());
        result = prime * result + ((getUpgradeDesc() == null) ? 0 : getUpgradeDesc().hashCode());
        result = prime * result + ((getPlatformType() == null) ? 0 : getPlatformType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}