package com.manager.pojo;

import com.manager.request.BaseEntity;
import java.util.Date;

public class HotCity extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.id
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.update_time
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.create_time
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_city.hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    private String hotCity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.id
     *
     * @return the value of hot_city.id
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.id
     *
     * @param id the value for hot_city.id
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.update_time
     *
     * @return the value of hot_city.update_time
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.update_time
     *
     * @param updateTime the value for hot_city.update_time
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.create_time
     *
     * @return the value of hot_city.create_time
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.create_time
     *
     * @param createTime the value for hot_city.create_time
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_city.hot_city
     *
     * @return the value of hot_city.hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    public String getHotCity() {
        return hotCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_city.hot_city
     *
     * @param hotCity the value for hot_city.hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    public void setHotCity(String hotCity) {
        this.hotCity = hotCity == null ? null : hotCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HotCity other = (HotCity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getHotCity() == null ? other.getHotCity() == null : this.getHotCity().equals(other.getHotCity()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_city
     *
     * @mbggenerated Fri May 26 14:13:31 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getHotCity() == null) ? 0 : getHotCity().hashCode());
        return result;
    }
}