package com.manager.pojo;

import com.manager.enums.YesNoEnum;
import com.manager.request.BaseEntity;

public class UserCustom extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.id
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.user_id
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.send_province
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private String sendProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.send_city
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private String sendCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.receive_province
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private String receiveProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.receive_city
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private String receiveCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_send
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private YesNoEnum isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_receive
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private YesNoEnum isReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_receive_self
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    private YesNoEnum isReceiveSelf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.id
     *
     * @return the value of user_custom.id
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.id
     *
     * @param id the value for user_custom.id
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.user_id
     *
     * @return the value of user_custom.user_id
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.user_id
     *
     * @param userId the value for user_custom.user_id
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.send_province
     *
     * @return the value of user_custom.send_province
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public String getSendProvince() {
        return sendProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.send_province
     *
     * @param sendProvince the value for user_custom.send_province
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setSendProvince(String sendProvince) {
        this.sendProvince = sendProvince == null ? null : sendProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.send_city
     *
     * @return the value of user_custom.send_city
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.send_city
     *
     * @param sendCity the value for user_custom.send_city
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setSendCity(String sendCity) {
        this.sendCity = sendCity == null ? null : sendCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.receive_province
     *
     * @return the value of user_custom.receive_province
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public String getReceiveProvince() {
        return receiveProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.receive_province
     *
     * @param receiveProvince the value for user_custom.receive_province
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setReceiveProvince(String receiveProvince) {
        this.receiveProvince = receiveProvince == null ? null : receiveProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.receive_city
     *
     * @return the value of user_custom.receive_city
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public String getReceiveCity() {
        return receiveCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.receive_city
     *
     * @param receiveCity the value for user_custom.receive_city
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setReceiveCity(String receiveCity) {
        this.receiveCity = receiveCity == null ? null : receiveCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_send
     *
     * @return the value of user_custom.is_send
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public YesNoEnum getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_send
     *
     * @param isSend the value for user_custom.is_send
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setIsSend(YesNoEnum isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_receive
     *
     * @return the value of user_custom.is_receive
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public YesNoEnum getIsReceive() {
        return isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_receive
     *
     * @param isReceive the value for user_custom.is_receive
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setIsReceive(YesNoEnum isReceive) {
        this.isReceive = isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_receive_self
     *
     * @return the value of user_custom.is_receive_self
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public YesNoEnum getIsReceiveSelf() {
        return isReceiveSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_receive_self
     *
     * @param isReceiveSelf the value for user_custom.is_receive_self
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    public void setIsReceiveSelf(YesNoEnum isReceiveSelf) {
        this.isReceiveSelf = isReceiveSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserCustom other = (UserCustom) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSendProvince() == null ? other.getSendProvince() == null : this.getSendProvince().equals(other.getSendProvince()))
            && (this.getSendCity() == null ? other.getSendCity() == null : this.getSendCity().equals(other.getSendCity()))
            && (this.getReceiveProvince() == null ? other.getReceiveProvince() == null : this.getReceiveProvince().equals(other.getReceiveProvince()))
            && (this.getReceiveCity() == null ? other.getReceiveCity() == null : this.getReceiveCity().equals(other.getReceiveCity()))
            && (this.getIsSend() == null ? other.getIsSend() == null : this.getIsSend().equals(other.getIsSend()))
            && (this.getIsReceive() == null ? other.getIsReceive() == null : this.getIsReceive().equals(other.getIsReceive()))
            && (this.getIsReceiveSelf() == null ? other.getIsReceiveSelf() == null : this.getIsReceiveSelf().equals(other.getIsReceiveSelf()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Mon Apr 10 12:02:01 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSendProvince() == null) ? 0 : getSendProvince().hashCode());
        result = prime * result + ((getSendCity() == null) ? 0 : getSendCity().hashCode());
        result = prime * result + ((getReceiveProvince() == null) ? 0 : getReceiveProvince().hashCode());
        result = prime * result + ((getReceiveCity() == null) ? 0 : getReceiveCity().hashCode());
        result = prime * result + ((getIsSend() == null) ? 0 : getIsSend().hashCode());
        result = prime * result + ((getIsReceive() == null) ? 0 : getIsReceive().hashCode());
        result = prime * result + ((getIsReceiveSelf() == null) ? 0 : getIsReceiveSelf().hashCode());
        return result;
    }
}