package com.manager.pojo;

import com.manager.enums.ManagerTypeEnum;
import com.manager.enums.PlatformTypeEnum;
import com.manager.enums.YesNoEnum;
import com.manager.request.BaseEntity;

public class UserCustom extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.user_id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.send_province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String sendProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.send_city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String sendCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.receive_province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String receiveProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.receive_city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String receiveCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_send
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_receive
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_receive_self
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isReceiveSelf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_manager
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private ManagerTypeEnum isManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.username
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.platform_type
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private PlatformTypeEnum platformType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_binding
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isBinding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_phone_limit
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isPhoneLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_receive_car
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isReceiveCar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_receive_goods
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isReceiveGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_send_car
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isSendCar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_send_goods
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isSendGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_custom.is_look_phone
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isLookPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.id
     *
     * @return the value of user_custom.id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.id
     *
     * @param id the value for user_custom.id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.user_id
     *
     * @return the value of user_custom.user_id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.user_id
     *
     * @param userId the value for user_custom.user_id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.send_province
     *
     * @return the value of user_custom.send_province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getSendProvince() {
        return sendProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.send_province
     *
     * @param sendProvince the value for user_custom.send_province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setSendProvince(String sendProvince) {
        this.sendProvince = sendProvince == null ? null : sendProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.send_city
     *
     * @return the value of user_custom.send_city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getSendCity() {
        return sendCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.send_city
     *
     * @param sendCity the value for user_custom.send_city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setSendCity(String sendCity) {
        this.sendCity = sendCity == null ? null : sendCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.receive_province
     *
     * @return the value of user_custom.receive_province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getReceiveProvince() {
        return receiveProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.receive_province
     *
     * @param receiveProvince the value for user_custom.receive_province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setReceiveProvince(String receiveProvince) {
        this.receiveProvince = receiveProvince == null ? null : receiveProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.receive_city
     *
     * @return the value of user_custom.receive_city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getReceiveCity() {
        return receiveCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.receive_city
     *
     * @param receiveCity the value for user_custom.receive_city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setReceiveCity(String receiveCity) {
        this.receiveCity = receiveCity == null ? null : receiveCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_send
     *
     * @return the value of user_custom.is_send
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_send
     *
     * @param isSend the value for user_custom.is_send
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsSend(YesNoEnum isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_receive
     *
     * @return the value of user_custom.is_receive
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsReceive() {
        return isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_receive
     *
     * @param isReceive the value for user_custom.is_receive
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsReceive(YesNoEnum isReceive) {
        this.isReceive = isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_receive_self
     *
     * @return the value of user_custom.is_receive_self
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsReceiveSelf() {
        return isReceiveSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_receive_self
     *
     * @param isReceiveSelf the value for user_custom.is_receive_self
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsReceiveSelf(YesNoEnum isReceiveSelf) {
        this.isReceiveSelf = isReceiveSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_manager
     *
     * @return the value of user_custom.is_manager
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public ManagerTypeEnum getIsManager() {
        return isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_manager
     *
     * @param isManager the value for user_custom.is_manager
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsManager(ManagerTypeEnum isManager) {
        this.isManager = isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.username
     *
     * @return the value of user_custom.username
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.username
     *
     * @param username the value for user_custom.username
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.platform_type
     *
     * @return the value of user_custom.platform_type
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public PlatformTypeEnum getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.platform_type
     *
     * @param platformType the value for user_custom.platform_type
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setPlatformType(PlatformTypeEnum platformType) {
        this.platformType = platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_binding
     *
     * @return the value of user_custom.is_binding
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsBinding() {
        return isBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_binding
     *
     * @param isBinding the value for user_custom.is_binding
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsBinding(YesNoEnum isBinding) {
        this.isBinding = isBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_phone_limit
     *
     * @return the value of user_custom.is_phone_limit
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsPhoneLimit() {
        return isPhoneLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_phone_limit
     *
     * @param isPhoneLimit the value for user_custom.is_phone_limit
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsPhoneLimit(YesNoEnum isPhoneLimit) {
        this.isPhoneLimit = isPhoneLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_receive_car
     *
     * @return the value of user_custom.is_receive_car
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsReceiveCar() {
        return isReceiveCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_receive_car
     *
     * @param isReceiveCar the value for user_custom.is_receive_car
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsReceiveCar(YesNoEnum isReceiveCar) {
        this.isReceiveCar = isReceiveCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_receive_goods
     *
     * @return the value of user_custom.is_receive_goods
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsReceiveGoods() {
        return isReceiveGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_receive_goods
     *
     * @param isReceiveGoods the value for user_custom.is_receive_goods
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsReceiveGoods(YesNoEnum isReceiveGoods) {
        this.isReceiveGoods = isReceiveGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_send_car
     *
     * @return the value of user_custom.is_send_car
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsSendCar() {
        return isSendCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_send_car
     *
     * @param isSendCar the value for user_custom.is_send_car
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsSendCar(YesNoEnum isSendCar) {
        this.isSendCar = isSendCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_send_goods
     *
     * @return the value of user_custom.is_send_goods
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsSendGoods() {
        return isSendGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_send_goods
     *
     * @param isSendGoods the value for user_custom.is_send_goods
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsSendGoods(YesNoEnum isSendGoods) {
        this.isSendGoods = isSendGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_custom.is_look_phone
     *
     * @return the value of user_custom.is_look_phone
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsLookPhone() {
        return isLookPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_custom.is_look_phone
     *
     * @param isLookPhone the value for user_custom.is_look_phone
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsLookPhone(YesNoEnum isLookPhone) {
        this.isLookPhone = isLookPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserCustom other = (UserCustom) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSendProvince() == null ? other.getSendProvince() == null : this.getSendProvince().equals(other.getSendProvince()))
            && (this.getSendCity() == null ? other.getSendCity() == null : this.getSendCity().equals(other.getSendCity()))
            && (this.getReceiveProvince() == null ? other.getReceiveProvince() == null : this.getReceiveProvince().equals(other.getReceiveProvince()))
            && (this.getReceiveCity() == null ? other.getReceiveCity() == null : this.getReceiveCity().equals(other.getReceiveCity()))
            && (this.getIsSend() == null ? other.getIsSend() == null : this.getIsSend().equals(other.getIsSend()))
            && (this.getIsReceive() == null ? other.getIsReceive() == null : this.getIsReceive().equals(other.getIsReceive()))
            && (this.getIsReceiveSelf() == null ? other.getIsReceiveSelf() == null : this.getIsReceiveSelf().equals(other.getIsReceiveSelf()))
            && (this.getIsManager() == null ? other.getIsManager() == null : this.getIsManager().equals(other.getIsManager()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPlatformType() == null ? other.getPlatformType() == null : this.getPlatformType().equals(other.getPlatformType()))
            && (this.getIsBinding() == null ? other.getIsBinding() == null : this.getIsBinding().equals(other.getIsBinding()))
            && (this.getIsPhoneLimit() == null ? other.getIsPhoneLimit() == null : this.getIsPhoneLimit().equals(other.getIsPhoneLimit()))
            && (this.getIsReceiveCar() == null ? other.getIsReceiveCar() == null : this.getIsReceiveCar().equals(other.getIsReceiveCar()))
            && (this.getIsReceiveGoods() == null ? other.getIsReceiveGoods() == null : this.getIsReceiveGoods().equals(other.getIsReceiveGoods()))
            && (this.getIsSendCar() == null ? other.getIsSendCar() == null : this.getIsSendCar().equals(other.getIsSendCar()))
            && (this.getIsSendGoods() == null ? other.getIsSendGoods() == null : this.getIsSendGoods().equals(other.getIsSendGoods()))
            && (this.getIsLookPhone() == null ? other.getIsLookPhone() == null : this.getIsLookPhone().equals(other.getIsLookPhone()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_custom
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSendProvince() == null) ? 0 : getSendProvince().hashCode());
        result = prime * result + ((getSendCity() == null) ? 0 : getSendCity().hashCode());
        result = prime * result + ((getReceiveProvince() == null) ? 0 : getReceiveProvince().hashCode());
        result = prime * result + ((getReceiveCity() == null) ? 0 : getReceiveCity().hashCode());
        result = prime * result + ((getIsSend() == null) ? 0 : getIsSend().hashCode());
        result = prime * result + ((getIsReceive() == null) ? 0 : getIsReceive().hashCode());
        result = prime * result + ((getIsReceiveSelf() == null) ? 0 : getIsReceiveSelf().hashCode());
        result = prime * result + ((getIsManager() == null) ? 0 : getIsManager().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPlatformType() == null) ? 0 : getPlatformType().hashCode());
        result = prime * result + ((getIsBinding() == null) ? 0 : getIsBinding().hashCode());
        result = prime * result + ((getIsPhoneLimit() == null) ? 0 : getIsPhoneLimit().hashCode());
        result = prime * result + ((getIsReceiveCar() == null) ? 0 : getIsReceiveCar().hashCode());
        result = prime * result + ((getIsReceiveGoods() == null) ? 0 : getIsReceiveGoods().hashCode());
        result = prime * result + ((getIsSendCar() == null) ? 0 : getIsSendCar().hashCode());
        result = prime * result + ((getIsSendGoods() == null) ? 0 : getIsSendGoods().hashCode());
        result = prime * result + ((getIsLookPhone() == null) ? 0 : getIsLookPhone().hashCode());
        return result;
    }
}