package com.manager.pojo;

import com.manager.enums.YesNoEnum;
import com.manager.request.BaseEntity;

public class UserBinding extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.user_id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.user_name
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.hardpan_num
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private String hardpanNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.network_card
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private String networkCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.temporary_card
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private String temporaryCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_binding.is_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    private YesNoEnum isBinding;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.id
     *
     * @return the value of user_binding.id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.id
     *
     * @param id the value for user_binding.id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.user_id
     *
     * @return the value of user_binding.user_id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.user_id
     *
     * @param userId the value for user_binding.user_id
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.user_name
     *
     * @return the value of user_binding.user_name
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.user_name
     *
     * @param userName the value for user_binding.user_name
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.hardpan_num
     *
     * @return the value of user_binding.hardpan_num
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public String getHardpanNum() {
        return hardpanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.hardpan_num
     *
     * @param hardpanNum the value for user_binding.hardpan_num
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setHardpanNum(String hardpanNum) {
        this.hardpanNum = hardpanNum == null ? null : hardpanNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.network_card
     *
     * @return the value of user_binding.network_card
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public String getNetworkCard() {
        return networkCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.network_card
     *
     * @param networkCard the value for user_binding.network_card
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setNetworkCard(String networkCard) {
        this.networkCard = networkCard == null ? null : networkCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.temporary_card
     *
     * @return the value of user_binding.temporary_card
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public String getTemporaryCard() {
        return temporaryCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.temporary_card
     *
     * @param temporaryCard the value for user_binding.temporary_card
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setTemporaryCard(String temporaryCard) {
        this.temporaryCard = temporaryCard == null ? null : temporaryCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_binding.is_binding
     *
     * @return the value of user_binding.is_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public YesNoEnum getIsBinding() {
        return isBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_binding.is_binding
     *
     * @param isBinding the value for user_binding.is_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    public void setIsBinding(YesNoEnum isBinding) {
        this.isBinding = isBinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBinding other = (UserBinding) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getHardpanNum() == null ? other.getHardpanNum() == null : this.getHardpanNum().equals(other.getHardpanNum()))
            && (this.getNetworkCard() == null ? other.getNetworkCard() == null : this.getNetworkCard().equals(other.getNetworkCard()))
            && (this.getTemporaryCard() == null ? other.getTemporaryCard() == null : this.getTemporaryCard().equals(other.getTemporaryCard()))
            && (this.getIsBinding() == null ? other.getIsBinding() == null : this.getIsBinding().equals(other.getIsBinding()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_binding
     *
     * @mbggenerated Sat Apr 01 12:32:06 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getHardpanNum() == null) ? 0 : getHardpanNum().hashCode());
        result = prime * result + ((getNetworkCard() == null) ? 0 : getNetworkCard().hashCode());
        result = prime * result + ((getTemporaryCard() == null) ? 0 : getTemporaryCard().hashCode());
        result = prime * result + ((getIsBinding() == null) ? 0 : getIsBinding().hashCode());
        return result;
    }
}