package com.manager.pojo;

import com.manager.enums.ManagerTypeEnum;
import com.manager.enums.PlatformTypeEnum;
import com.manager.enums.YesNoEnum;
import com.manager.request.BaseEntity;
import java.util.Date;

public class User extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String userNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password_confirm
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String passwordConfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phones
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String phones;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.district
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.begin_time
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.end_time
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_manager
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private ManagerTypeEnum isManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_synchro
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private YesNoEnum isSynchro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mailbox
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String mailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.post_code
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company_name
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.register_ip
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_ip
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identification
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String identification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_quit_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String lastQuitNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.this_load_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String thisLoadNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.check_limit
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private Integer checkLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.check_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private Integer checkNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.platform_type
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private PlatformTypeEnum platformType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.registrationID
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String registrationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.in_line
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    private String inLine;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_num
     *
     * @return the value of user.user_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_num
     *
     * @param userNum the value for user.user_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password_confirm
     *
     * @return the value of user.password_confirm
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getPasswordConfirm() {
        return passwordConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password_confirm
     *
     * @param passwordConfirm the value for user.password_confirm
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setPasswordConfirm(String passwordConfirm) {
        this.passwordConfirm = passwordConfirm == null ? null : passwordConfirm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phones
     *
     * @return the value of user.phones
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getPhones() {
        return phones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phones
     *
     * @param phones the value for user.phones
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setPhones(String phones) {
        this.phones = phones == null ? null : phones.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province
     *
     * @return the value of user.province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province
     *
     * @param province the value for user.province
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.district
     *
     * @return the value of user.district
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.district
     *
     * @param district the value for user.district
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.begin_time
     *
     * @return the value of user.begin_time
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.begin_time
     *
     * @param beginTime the value for user.begin_time
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.end_time
     *
     * @return the value of user.end_time
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.end_time
     *
     * @param endTime the value for user.end_time
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setStatus(YesNoEnum status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_manager
     *
     * @return the value of user.is_manager
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public ManagerTypeEnum getIsManager() {
        return isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_manager
     *
     * @param isManager the value for user.is_manager
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsManager(ManagerTypeEnum isManager) {
        this.isManager = isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_synchro
     *
     * @return the value of user.is_synchro
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public YesNoEnum getIsSynchro() {
        return isSynchro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_synchro
     *
     * @param isSynchro the value for user.is_synchro
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIsSynchro(YesNoEnum isSynchro) {
        this.isSynchro = isSynchro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mailbox
     *
     * @return the value of user.mailbox
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mailbox
     *
     * @param mailbox the value for user.mailbox
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox == null ? null : mailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.post_code
     *
     * @return the value of user.post_code
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.post_code
     *
     * @param postCode the value for user.post_code
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company_name
     *
     * @return the value of user.company_name
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company_name
     *
     * @param companyName the value for user.company_name
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.register_ip
     *
     * @return the value of user.register_ip
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.register_ip
     *
     * @param registerIp the value for user.register_ip
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_ip
     *
     * @return the value of user.login_ip
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_ip
     *
     * @param loginIp the value for user.login_ip
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identification
     *
     * @return the value of user.identification
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identification
     *
     * @param identification the value for user.identification
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setIdentification(String identification) {
        this.identification = identification == null ? null : identification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_quit_num
     *
     * @return the value of user.last_quit_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getLastQuitNum() {
        return lastQuitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_quit_num
     *
     * @param lastQuitNum the value for user.last_quit_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setLastQuitNum(String lastQuitNum) {
        this.lastQuitNum = lastQuitNum == null ? null : lastQuitNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.this_load_num
     *
     * @return the value of user.this_load_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getThisLoadNum() {
        return thisLoadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.this_load_num
     *
     * @param thisLoadNum the value for user.this_load_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setThisLoadNum(String thisLoadNum) {
        this.thisLoadNum = thisLoadNum == null ? null : thisLoadNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.check_limit
     *
     * @return the value of user.check_limit
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public Integer getCheckLimit() {
        return checkLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.check_limit
     *
     * @param checkLimit the value for user.check_limit
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setCheckLimit(Integer checkLimit) {
        this.checkLimit = checkLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.check_num
     *
     * @return the value of user.check_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public Integer getCheckNum() {
        return checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.check_num
     *
     * @param checkNum the value for user.check_num
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setCheckNum(Integer checkNum) {
        this.checkNum = checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.platform_type
     *
     * @return the value of user.platform_type
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public PlatformTypeEnum getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.platform_type
     *
     * @param platformType the value for user.platform_type
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setPlatformType(PlatformTypeEnum platformType) {
        this.platformType = platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.registrationID
     *
     * @return the value of user.registrationID
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getRegistrationid() {
        return registrationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.registrationID
     *
     * @param registrationid the value for user.registrationID
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setRegistrationid(String registrationid) {
        this.registrationid = registrationid == null ? null : registrationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.in_line
     *
     * @return the value of user.in_line
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public String getInLine() {
        return inLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.in_line
     *
     * @param inLine the value for user.in_line
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    public void setInLine(String inLine) {
        this.inLine = inLine == null ? null : inLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getUserNum() == null ? other.getUserNum() == null : this.getUserNum().equals(other.getUserNum()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getPasswordConfirm() == null ? other.getPasswordConfirm() == null : this.getPasswordConfirm().equals(other.getPasswordConfirm()))
            && (this.getPhones() == null ? other.getPhones() == null : this.getPhones().equals(other.getPhones()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIsManager() == null ? other.getIsManager() == null : this.getIsManager().equals(other.getIsManager()))
            && (this.getIsSynchro() == null ? other.getIsSynchro() == null : this.getIsSynchro().equals(other.getIsSynchro()))
            && (this.getMailbox() == null ? other.getMailbox() == null : this.getMailbox().equals(other.getMailbox()))
            && (this.getPostCode() == null ? other.getPostCode() == null : this.getPostCode().equals(other.getPostCode()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getRegisterIp() == null ? other.getRegisterIp() == null : this.getRegisterIp().equals(other.getRegisterIp()))
            && (this.getLoginIp() == null ? other.getLoginIp() == null : this.getLoginIp().equals(other.getLoginIp()))
            && (this.getIdentification() == null ? other.getIdentification() == null : this.getIdentification().equals(other.getIdentification()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getLastQuitNum() == null ? other.getLastQuitNum() == null : this.getLastQuitNum().equals(other.getLastQuitNum()))
            && (this.getThisLoadNum() == null ? other.getThisLoadNum() == null : this.getThisLoadNum().equals(other.getThisLoadNum()))
            && (this.getCheckLimit() == null ? other.getCheckLimit() == null : this.getCheckLimit().equals(other.getCheckLimit()))
            && (this.getCheckNum() == null ? other.getCheckNum() == null : this.getCheckNum().equals(other.getCheckNum()))
            && (this.getPlatformType() == null ? other.getPlatformType() == null : this.getPlatformType().equals(other.getPlatformType()))
            && (this.getRegistrationid() == null ? other.getRegistrationid() == null : this.getRegistrationid().equals(other.getRegistrationid()))
            && (this.getInLine() == null ? other.getInLine() == null : this.getInLine().equals(other.getInLine()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Thu Apr 20 16:24:04 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getUserNum() == null) ? 0 : getUserNum().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getPasswordConfirm() == null) ? 0 : getPasswordConfirm().hashCode());
        result = prime * result + ((getPhones() == null) ? 0 : getPhones().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIsManager() == null) ? 0 : getIsManager().hashCode());
        result = prime * result + ((getIsSynchro() == null) ? 0 : getIsSynchro().hashCode());
        result = prime * result + ((getMailbox() == null) ? 0 : getMailbox().hashCode());
        result = prime * result + ((getPostCode() == null) ? 0 : getPostCode().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getRegisterIp() == null) ? 0 : getRegisterIp().hashCode());
        result = prime * result + ((getLoginIp() == null) ? 0 : getLoginIp().hashCode());
        result = prime * result + ((getIdentification() == null) ? 0 : getIdentification().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getLastQuitNum() == null) ? 0 : getLastQuitNum().hashCode());
        result = prime * result + ((getThisLoadNum() == null) ? 0 : getThisLoadNum().hashCode());
        result = prime * result + ((getCheckLimit() == null) ? 0 : getCheckLimit().hashCode());
        result = prime * result + ((getCheckNum() == null) ? 0 : getCheckNum().hashCode());
        result = prime * result + ((getPlatformType() == null) ? 0 : getPlatformType().hashCode());
        result = prime * result + ((getRegistrationid() == null) ? 0 : getRegistrationid().hashCode());
        result = prime * result + ((getInLine() == null) ? 0 : getInLine().hashCode());
        return result;
    }
}